{{- $authPassword := and .Values.auth.password (not .Values.auth.existingSecret) -}}
{{- $pcpPassword := and .Values.pcp.password (not .Values.pcp.existingSecret) -}}
{{- if or $authPassword $pcpPassword }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pgpool.fullname" . }}
  labels:
    {{- include "pgpool.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if $authPassword }}
  password: {{ .Values.auth.password | quote }}
  {{- end }}
  {{- if $pcpPassword }}
  pcp-password: {{ .Values.pcp.password | quote }}
  {{- end }}
{{- end }}
